name: Run init.py and Create Artifact

on:
  workflow_dispatch:
    inputs:
      client:
        description: 'Your GitHub username'
        required: true
      webhook:
        description: 'Environment for deployment (dev, prod)'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install required packages
        run: |
          pip install pip --upgrade
          pip install pywin32 requests pycryptodomex pyinstaller cryptography

      - name: Init everything
        env:
          CLIENT: ${{ github.event.inputs.client }}
          WEBHOOK: ${{ github.event.inputs.webhook }}
          KEY: ${{ secrets.KEY }}
        run: |
          python init.py

      - name: Create artifact of the current directory
        uses: actions/upload-artifact@v3
        with:
          name: current-directory-artifact
          path: .  # This will upload the entire current directory

